name: ready to merge services
run-name: GitHub Actions 🚀
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        service: ['services/investments', 'services/host']
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run Prettier
        run: npm run format
        working-directory: ${{ matrix.service }}
      - name: Run Typecheck
        run: npm run typecheck
        working-directory: ${{ matrix.service }}
      - name: Run ESLint
        run: npm run lint
        working-directory: ${{ matrix.service }}
      - name: Run test
        run: npm run test
        working-directory: ${{ matrix.service }}
      - name: Run build
        run: npm run build:prod
        working-directory: ${{ matrix.service }}
